### ISSUE TITLE
About page for website portfolio 

### ISSUE THREAD

**Issue by osan0004** [osan0004/portfolio#1]
@AbhaySharma

Hey Abhay,

About my website portfolio, I'm having issues with aligning the skewer, It's being pushed to the bottom of the page, and I'm pretty sure i added the class to the right place

**Comment by abhaysharma** [comment]
@osan0004 here are the steps to take:
- change position from absolute to relative for `.skewer` around `line: 278` in your CSS
- Also add `background-color: #994505` to `.skewer`

**Comment by osan0004** [comment]
@abhaysharma Thanks allot! I've been able to fix it

**Comment by abhaysharma** [comment]
@osan0004 perfect! you can close the issue now.
