### ISSUE TITLE
 Carousel menu

### ISSUE THREAD

**Issue by osan0004** [osan0004/portfolio#2]
Hello @abhaysharma, I'm having this issue with my carousel menu where as it scrolls it's going over the boundaries. I've tried changing some values and researching but I'm not sure what the issue is. Could you please take a look at it. 
Thanks.

**Comment by abhaysharma** [comment]
@osan0004 please send me a screenshot.

**Comment by osan0004** [comment]
@abhaysharma This jump happens on mobile and tablet screen sizes, on desktop it works fine. I used a responsive carousel menu for this.

![Screenshot 2023-12-12 105942](https://github.com/osan0004/portfolio/assets/133021369/877b646f-d842-487c-b8cc-3347c52eb594)
![image](https://github.com/osan0004/portfolio/assets/133021369/91ac46a2-9f95-472e-861a-23ef1c0c3916)

**Comment by abhaysharma** [comment]
@osan0004 when I inspect the image that is mialigned it has a padding on top added to an active class. If you need that padding for another element you will need to be more specific. media-query.css file `line:3`

**Comment by osan0004** [comment]
@abhaysharma Oh wow I completely missed that. I've fixed it. Thanks allot. 
I'll close the issue.
